-- ==============================================================================
-- VELORA WEB SOLUTIONS - SUPABASE DATABASE SCHEMA (SECURITY-HARDENED)
-- Run this in Supabase SQL Editor: Dashboard -> SQL Editor -> New Query
--
-- WHY THIS FILE EXISTS
-- The original schema.sql granted the PUBLIC "anon" role permission to
-- SELECT, INSERT, and DELETE on `inquiries`, and to do ANYTHING (SELECT +
-- INSERT + UPDATE + DELETE) on `site_settings`, with USING (true) / WITH
-- CHECK (true) — i.e. no restriction at all. Combined with the Supabase
-- URL + anon key being hardcoded in supabase.js (which is unavoidable for
-- a static site, and is normally fine), this meant ANY visitor could:
--   - read every lead/inquiry ever submitted (names, phone numbers, notes)
--   - delete all leads
--   - overwrite your live site content (site_settings) with anything,
--     bypassing the admin.html passcode entirely, since that passcode is
--     only a client-side JS check and never touches Supabase permissions.
--
-- FIX: anonymous (anon) visitors can still submit inquiries (INSERT only —
-- required for the public contact form). Reading/deleting inquiries and
-- writing site_settings now requires a real authenticated Supabase user.
-- You'll need to create a Supabase Auth login (email/password is fine) for
-- yourself and gate admin.html behind supabase.auth.signInWithPassword(),
-- replacing the current localStorage passcode check, or this table will
-- simply be unreadable/unwritable by your own admin panel too.
-- ==============================================================================

-- 1. 'inquiries' table for storing client leads & form submissions
CREATE TABLE IF NOT EXISTS inquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT,
  website_type TEXT,
  budget TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE inquiries ENABLE ROW LEVEL SECURITY;

-- Drop the old, overly-permissive policies if they exist
DROP POLICY IF EXISTS "Allow public insert to inquiries" ON inquiries;
DROP POLICY IF EXISTS "Allow public read from inquiries" ON inquiries;
DROP POLICY IF EXISTS "Allow public delete from inquiries" ON inquiries;

-- Anonymous visitors may SUBMIT a lead (this is the public contact form) ...
CREATE POLICY "anon_insert_inquiries"
ON inquiries FOR INSERT
TO anon
WITH CHECK (true);

-- ...but only a logged-in (authenticated) admin can read leads back
CREATE POLICY "auth_read_inquiries"
ON inquiries FOR SELECT
TO authenticated
USING (true);

-- ...and only a logged-in admin can delete leads
CREATE POLICY "auth_delete_inquiries"
ON inquiries FOR DELETE
TO authenticated
USING (true);


-- 2. 'site_settings' table for Cloud CMS syncing
CREATE TABLE IF NOT EXISTS site_settings (
  id TEXT PRIMARY KEY,
  data JSONB NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE site_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read from site_settings" ON site_settings;
DROP POLICY IF EXISTS "Allow public insert and update to site_settings" ON site_settings;

-- Anyone (including anonymous site visitors) may READ settings —
-- this is what makes the public website render your saved content.
CREATE POLICY "anon_read_site_settings"
ON site_settings FOR SELECT
TO anon, authenticated
USING (true);

-- Only a logged-in admin can write settings (this is what admin.html needs).
CREATE POLICY "auth_write_site_settings"
ON site_settings FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);
