-- ==============================================================================
-- VELORA WEB SOLUTIONS - SUPABASE DATABASE SCHEMA
-- Run this SQL in your Supabase SQL Editor: Dashboard -> SQL Editor -> New Query
-- ==============================================================================

-- 1. Create 'inquiries' table for storing client leads & form submissions
CREATE TABLE IF NOT EXISTS inquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT,
  website_type TEXT,
  budget TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE inquiries ENABLE ROW LEVEL SECURITY;

-- Allow public anonymous visitors to insert inquiries
CREATE POLICY "Allow public insert to inquiries" 
ON inquiries FOR INSERT 
TO anon, authenticated 
WITH CHECK (true);

-- Allow public / admin to view inquiries
CREATE POLICY "Allow public read from inquiries" 
ON inquiries FOR SELECT 
TO anon, authenticated 
USING (true);

-- Allow public / admin to delete inquiries
CREATE POLICY "Allow public delete from inquiries" 
ON inquiries FOR DELETE 
TO anon, authenticated 
USING (true);


-- 2. Create 'site_settings' table for Cloud CMS syncing
CREATE TABLE IF NOT EXISTS site_settings (
  id TEXT PRIMARY KEY,
  data JSONB NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE site_settings ENABLE ROW LEVEL SECURITY;

-- Allow public / admin to read site settings
CREATE POLICY "Allow public read from site_settings" 
ON site_settings FOR SELECT 
TO anon, authenticated 
USING (true);

-- Allow public / admin to insert & update site settings
CREATE POLICY "Allow public insert and update to site_settings" 
ON site_settings FOR ALL 
TO anon, authenticated 
USING (true) 
WITH CHECK (true);
